repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: check-json
      - id: pretty-format-json
        args:
          - --autofix
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args:
          - --fix
          - --exit-non-zero-on-fix
      - id: ruff-format

  # - repo: https://github.com/adamchainz/django-upgrade
  #   rev: 1.19.0
  #   hooks:
  #     - id: django-upgrade

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        name: mypy-app
        files: ^backend/
        exclude: (?x)(
            ^backend/tests/|
            /migrations/
          )
        args:
          - --install-types
          - --non-interactive
          - --no-namespace-packages
        # additional_dependencies:
        #   - django
        #   - djangorestframework
        #   - django-stubs
        #   - djangorestframework-stubs
        #   - python-decouple-stubs
        entry: env MYPYPATH=backend mypy --config-file=mypy.ini

      - id: mypy
        name: mypy-tests
        files: ^backend/tests/
        args:
          - --install-types
          - --non-interactive
          - --no-namespace-packages
        # additional_dependencies:
        #   - django
        #   - djangorestframework
        #   - django-stubs
        #   - djangorestframework-stubs
        #   - python-decouple-stubs
        #   - pytest
        #   - pytest-django
        #   - factory-boy
        entry: env MYPYPATH=backend mypy --config-file=mypy.ini
