# Generated by Django 5.2.7 on 2025-10-27 19:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("confidential", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecretViewLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "secret_uuid",
                    models.UUIDField(
                        db_index=True,
                        help_text="UUID of the secret (kept even after secret deletion)",
                    ),
                ),
                ("viewed_at", models.DateTimeField()),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="IP address of the viewer"),
                ),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "success",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the view was successful",
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("already_viewed", "Already Viewed"),
                            ("expired", "Expired"),
                            ("not_found", "Not Found"),
                            ("deleted", "Secret Deleted"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secret_view_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="confidential.secret",
                    ),
                ),
            ],
            options={
                "ordering": ["-viewed_at"],
                "indexes": [
                    models.Index(
                        fields=["creator", "-viewed_at"],
                        name="confidentia_creator_995b46_idx",
                    ),
                    models.Index(
                        fields=["secret_uuid", "-viewed_at"],
                        name="confidentia_secret__af28b4_idx",
                    ),
                    models.Index(
                        fields=["success", "-viewed_at"],
                        name="confidentia_success_6ddea3_idx",
                    ),
                ],
            },
        ),
    ]
